const path = require("node:path");

const { ROOT } = require("../lib/config");
const { ensureDir, getUniquePath, readJson, writeJson } = require("../lib/fsx");

const TEMPLATE_DIR = path.join(ROOT, "docs", "ACTIVE", "INTENT_TEMPLATES");
const TEMPLATE_FILES = {
  SHOW_DASHBOARD: "intent_v2_noop.json",
  UPDATE_DASHBOARD_DATA_CASE_ADD: "intent_v2_case_add.json",
  UPDATE_DASHBOARD_DATA_CASE_UPDATE: "intent_v2_case_update.json",
};

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (!a.startsWith("--")) continue;
    const key = a.slice(2);
    const next = argv[i + 1];
    const value = next && !next.startsWith("--") ? argv[++i] : "true";
    args[key] = value;
    args[key.replace(/-/g, "_")] = value;
  }
  return args;
}

function splitCsv(value) {
  return String(value || "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

function nowIdToken() {
  return new Date().toISOString().replace(/[-:.TZ]/g, "");
}

function cloneJson(value) {
  return JSON.parse(JSON.stringify(value));
}

async function loadTemplateByType(type) {
  const key = String(type || "").toUpperCase();
  const file = TEMPLATE_FILES[key];
  if (!file) {
    throw new Error(
      `Unsupported --type ${type}. Use SHOW_DASHBOARD | UPDATE_DASHBOARD_DATA_CASE_ADD | UPDATE_DASHBOARD_DATA_CASE_UPDATE`,
    );
  }
  const fullPath = path.join(TEMPLATE_DIR, file);
  return readJson(fullPath);
}

async function buildIntent({
  type,
  case_id,
  title,
  aliases,
  tags,
  source = "ui:intent:new",
}) {
  const ts = new Date().toISOString();
  const token = nowIdToken();
  const normalizedType = String(type || "").toUpperCase();
  const template = cloneJson(await loadTemplateByType(normalizedType));

  template.id = normalizedType === "SHOW_DASHBOARD"
    ? `intent_ui_show_${token}`
    : normalizedType === "UPDATE_DASHBOARD_DATA_CASE_ADD"
      ? `intent_ui_case_add_${token}`
      : `intent_ui_case_update_${token}`;
  template.ts = ts;
  template.source = source;
  template.status = "new";

  if (normalizedType === "SHOW_DASHBOARD") {
    template.payload = {
      ...(template.payload && typeof template.payload === "object" ? template.payload : {}),
      note: "Generated by ui:intent:new",
    };
    return template;
  }

  if (normalizedType === "UPDATE_DASHBOARD_DATA_CASE_ADD") {
    if (!case_id) throw new Error("--case_id is required for case add");
    template.payload = {
      ...(template.payload && typeof template.payload === "object" ? template.payload : {}),
      registry_case_add: {
        case_id,
        title: title || case_id,
        aliases,
        tags,
      },
    };
    return template;
  }

  if (normalizedType === "UPDATE_DASHBOARD_DATA_CASE_UPDATE") {
    if (!case_id) throw new Error("--case_id is required for case update");
    template.payload = {
      ...(template.payload && typeof template.payload === "object" ? template.payload : {}),
      registry_case_update: {
        case_id,
        title: title || case_id,
        aliases,
        tags,
      },
    };
    return template;
  }

  throw new Error(
    `Unsupported --type ${type}. Use SHOW_DASHBOARD | UPDATE_DASHBOARD_DATA_CASE_ADD | UPDATE_DASHBOARD_DATA_CASE_UPDATE`,
  );
}

async function createUiIntent({
  root = ROOT,
  type,
  case_id = "",
  title = "",
  aliases = [],
  tags = [],
  source = "ui:intent:new",
} = {}) {
  const absRoot = path.resolve(root);
  const intentsDir = path.join(absRoot, "60_intents");
  await ensureDir(intentsDir);

  const intent = await buildIntent({
    type,
    case_id,
    title,
    aliases,
    tags,
    source,
  });

  const basePath = path.join(intentsDir, `${intent.id}.json`);
  const filePath = await getUniquePath(basePath);
  await writeJson(filePath, intent);

  return {
    ok: true,
    file: filePath,
    intent,
  };
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const type = args.type || "SHOW_DASHBOARD";
  const case_id = args.case_id || "";
  const title = args.title || "";
  const aliases = splitCsv(args.aliases);
  const tags = splitCsv(args.tags);
  const source = args.source || "ui:intent:new";

  const result = await createUiIntent({
    type,
    case_id,
    title,
    aliases,
    tags,
    source,
  });

  // eslint-disable-next-line no-console
  console.log(JSON.stringify({
    ok: result.ok,
    file: result.file,
    id: result.intent.id,
    type: result.intent.type,
    ts: result.intent.ts,
  }, null, 2));
}

if (require.main === module) {
  main().catch((error) => {
    // eslint-disable-next-line no-console
    console.error(error?.stack || error);
    process.exit(1);
  });
}

module.exports = {
  createUiIntent,
  buildIntent,
};
