const path = require("node:path");

const { ROOT } = require("../lib/config");
const { ensureDir, getUniquePath, readJson, writeJson } = require("../lib/fsx");

const TEMPLATE_DIR = path.join(ROOT, "docs", "ACTIVE", "INTENT_TEMPLATES");
const INTENTS_DIR = path.join(ROOT, "60_intents");

const TEMPLATE_BY_TYPE = {
  show_dashboard: "intent_v2_noop.json",
  case_add: "intent_v2_case_add.json",
  case_update: "intent_v2_case_update.json",
};

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (!arg.startsWith("--")) continue;
    const key = arg.slice(2);
    const next = argv[i + 1];
    const value = next && !next.startsWith("--") ? argv[++i] : "true";
    args[key] = value;
    args[key.replace(/-/g, "_")] = value;
  }
  return args;
}

function splitCsv(value) {
  return String(value || "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
}

function nowToken() {
  const d = new Date();
  const yyyy = String(d.getUTCFullYear());
  const mm = String(d.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(d.getUTCDate()).padStart(2, "0");
  const HH = String(d.getUTCHours()).padStart(2, "0");
  const MM = String(d.getUTCMinutes()).padStart(2, "0");
  const SS = String(d.getUTCSeconds()).padStart(2, "0");
  const mmm = String(d.getUTCMilliseconds()).padStart(3, "0");
  return `${yyyy}${mm}${dd}T${HH}${MM}${SS}${mmm}Z`;
}

function random4() {
  return Math.random().toString(36).slice(2, 6).padEnd(4, "0");
}

async function loadTemplate(type) {
  const key = String(type || "").toLowerCase();
  const file = TEMPLATE_BY_TYPE[key];
  if (!file) {
    throw new Error("Unsupported --type. Use: show_dashboard | case_add | case_update");
  }
  return readJson(path.join(TEMPLATE_DIR, file));
}

function cloneJson(value) {
  return JSON.parse(JSON.stringify(value));
}

function normalizeType(type) {
  const key = String(type || "").toLowerCase();
  if (!TEMPLATE_BY_TYPE[key]) {
    throw new Error("Unsupported --type. Use: show_dashboard | case_add | case_update");
  }
  return key;
}

async function createIntent({
  root = ROOT,
  type,
  case_id = "",
  title = "",
  aliases = [],
  tags = [],
  source = "ui:intent:new",
} = {}) {
  const absRoot = path.resolve(root);
  const normalized = normalizeType(type);
  const template = cloneJson(await loadTemplate(normalized));

  const token = nowToken();
  const intentId = `intent_${normalized}_${token}_${random4()}`;
  template.id = intentId;
  template.ts = new Date().toISOString();
  template.source = source;
  template.status = "new";

  if (normalized === "show_dashboard") {
    template.type = "SHOW_DASHBOARD";
    template.payload = {
      ...(template.payload && typeof template.payload === "object" ? template.payload : {}),
      note: "Generated by src/ui/intent_new.js",
    };
  }

  if (normalized === "case_add") {
    if (!case_id) throw new Error("--case_id is required for case_add");
    template.type = "UPDATE_DASHBOARD_DATA";
    template.payload = {
      ...(template.payload && typeof template.payload === "object" ? template.payload : {}),
      registry_case_add: {
        case_id,
        title: title || case_id,
        aliases,
        tags,
      },
    };
  }

  if (normalized === "case_update") {
    if (!case_id) throw new Error("--case_id is required for case_update");
    template.type = "UPDATE_DASHBOARD_DATA";
    template.payload = {
      ...(template.payload && typeof template.payload === "object" ? template.payload : {}),
      registry_case_update: {
        case_id,
        title: title || case_id,
        aliases,
        tags,
      },
    };
  }

  const intentsDir = path.join(absRoot, path.relative(ROOT, INTENTS_DIR));
  await ensureDir(intentsDir);
  const filename = `${token}__${intentId}.json`;
  const target = await getUniquePath(path.join(intentsDir, filename));
  await writeJson(target, template);

  return {
    ok: true,
    path: target,
    intent_id: intentId,
    filename: path.basename(target),
  };
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const type = args.type || "show_dashboard";

  const result = await createIntent({
    type,
    case_id: args.case_id || "",
    title: args.title || "",
    aliases: splitCsv(args.aliases),
    tags: splitCsv(args.tags),
    source: args.source || "ui:intent:new",
  });

  // eslint-disable-next-line no-console
  console.log(result.path);
}

if (require.main === module) {
  main().catch((error) => {
    // eslint-disable-next-line no-console
    console.error(error?.stack || error);
    process.exit(1);
  });
}

module.exports = {
  createIntent,
  nowToken,
  normalizeType,
};
